name: Windows x64
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Azul JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --no-transfer-progress -B test
